# Default values for reflow-ingress-logs.

settings:
  debug: false
  ingressController:
    label: "app.kubernetes.io/name=ingress-nginx"
    namespace: "ingress-nginx"

replicaCount: 1

image:
  repository: supporttools/reflow-ingress-logs
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: "dockerhub"
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "reflow-ingress-logs"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 32Mi

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Readiness and Liveness probes
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
  path: /healthz

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 1
  failureThreshold: 5
  successThreshold: 1
  path: /healthz
