# Default values for reflow-ingress-logs.

settings:
  debug: false
  ingressController:
    label: "app.kubernetes.io/name=ingress-nginx"
    namespace: "ingress-nginx"
    defaultLogFormat: true # If true, the default log format will be used. If false, use the custom log format. See the README for more information.

replicaCount: 1

image:
  repository: supporttools/reflow-ingress-logs
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: "dockerhub"
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "reflow-ingress-logs"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 32Mi

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
